name: Check Action Versions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check_action_versions:
    runs-on: ubuntu-latest
    steps:
      # Outdated action versions
      - uses: actions/checkout@v3
      - run: |
          pwd
          ls -la
      - uses: H00N24/uses-version-check@main
        with:
          files: action.yml .github
          ignore_version_regex: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
